//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public string LoginErrorMessage { get; internal set; }
        public object UserID { get; internal set; }
    }
}
